name: Static typechecking (mypy)

on:
  push:
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Static typechecking with mypy
      uses: tsuyoshicho/action-mypy@v3
